auto: true
url: "https://google.github.io"
baseurl: '/flogger'
markdown: kramdown
repository: google/flogger

title: Flogger
description:
  Flogger is a fluent logging API for Java. It supports a wide variety of
  features, and has many benefits over existing logging APIs.

themeColor: teal

exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _site
  - node_modules
  - vendor

sass:
  style: compressed

googleAnalyticsId: G-JXXD2N5D13

nav:
  - item:
      name: Home
      url: /
  - item:
      name: "Benefits"
      url: /benefits
  - item:
      name: "Best Practices"
      url: /best_practice
  - item:
      name: "Anatomy"
      url: /anatomy
